// Auto-generated by combine.py
// Please do not edit this file directly.

// Standard Libraries
#include <algorithm>
#include <cerrno>
#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <fstream>
#include <iostream>
#include <limits>
#include <string>
#include <vector>

// ================== Start of include/Defs.h ==================
#ifndef DEFS_H
#define DEFS_H

namespace Amazons {
const int GRIDSIZE = 8;
const int OBSTACLE = 2;
const int judge_black = 0;
const int judge_white = 1;
const int grid_black = 1;
const int grid_white = -1;
const int EMPTY = 0;

struct Point {
  int8_t x, y;
  bool operator==(const Point &other) const {
    return x == other.x && y == other.y;
  }
};

struct Move {
  Point start;
  Point target;
  Point arrow;
  bool operator==(const Move &other) const {
    return start == other.start && target == other.target &&
           arrow == other.arrow;
  }
};
const Move MOVE_EXIT = {-1, -1, -1, -1, -1, -1};
const Move MOVE_SAVE = {-2, -2, -2, -2, -2, -2};
const Move MOVE_NULL = {-3, -3, -3, -3, -3, -3};
const Move MOVE_LOSE = {-4, -4, -4, -4, -4, -4};

} // namespace Amazons

#endif // !DEFS_H

// ================== End of include/Defs.h ==================

// ================== Start of include/Board.h ==================
#ifndef BOARD_H
#define BOARD_H

namespace Amazons {
class Board {
private:
  int8_t grid[GRIDSIZE][GRIDSIZE];
  int turnID;
  Point blackPieces[4];
  Point whitePieces[4];

public:
  Board();                              // 用于初始化棋盘 1
  bool inMap(const Point &point) const; // 用于判断是否在棋盘范围内 1
  bool isEmpty(const Point &point) const; // 用于判断该点是否被占据 1
  int getGrid(const Point &point) const;
  int getTurnID() const;
  const Point *getPieces(int color) const;
  void applyMove(const Move &move,
                 int color); // 执行一步，改变棋盘状态 1
  std::vector<Move>
  getLegalMoves(int color) const; // 获取所有合法走法，返回一个vector 1
  int countLegalMoves(int color) const;       // 1
  void undoMove(const Move &move, int color); // 1
  int loadBoard(const std::string &filename); // 返回人类玩家的颜色
  void addTurnID() { turnID++; }
};
} // namespace Amazons
#endif // !BOARD_H

// ================== End of include/Board.h ==================

// ================== Start of include/Player.h ==================
#ifndef AI_H
#define AI_H

namespace Amazons {
class Player {
protected:
  int myColor;

public:
  Player(int c) : myColor(c) {}
  virtual ~Player() {}
  virtual Move decideMove(const Board &board) = 0;
  virtual bool isBot();
};
class AIPlayer : public Player {
private:
  void queenBFS(const Board &board, int (*map)[8], int isMyself);
  int evaluate(const Board &board);
  int countMobility(const Board &board);
  int calQueenTerritory(const Board &board, int myMap[GRIDSIZE][GRIDSIZE],
                        int opMap[GRIDSIZE][GRIDSIZE]);
  int calTrapPenalty(const Board &board, int isMyself,
                     int myMap[GRIDSIZE][GRIDSIZE],
                     int opMap[GRIDSIZE][GRIDSIZE]);
  int calPosValue(const Board &board);
  int minimax(const Board &board, int depth, bool isMaximizing, int alpha,
              int beta);

public:
  AIPlayer(int c) : Player(c) {}
  ~AIPlayer() {}
  Move decideMove(const Board &board);
  bool isBot() { return true; }
};
class humanPlayer : public Player {
public:
  humanPlayer(int c) : Player(c) {}
  ~humanPlayer() {}
  Move decideMove(const Board &board);
  bool isBot() { return false; }
};
} // namespace Amazons
#endif

// ================== End of include/Player.h ==================

// ================== Start of include/Interaction.h ==================
#ifndef INTERACTION_H
#define INTERACTION_H

namespace Amazons {
namespace Interaction {
int initAndRestore(Board &board);
void outputMove(const Move &move);
} // namespace Interaction
} // namespace Amazons

#endif

// ================== End of include/Interaction.h ==================

// ================== Start of include/UI.h ==================
#ifndef UI_H
#define UI_H

namespace Amazons {
class Game {
public:
  void run();
  Game();
  ~Game();

private:
  Board board;
  Player *blackPlayer;
  Player *whitePlayer;
  int humanColor;

  void showMenu();               // 显示主菜单 1
  void startNewGame();           // 开始新游戏 1
  void gameLoop(int startColor); // 对战循环 1

  void renderBoard(); // 画棋盘 1

  void saveGame(const std::string &filename);
  void loadGame(const std::string &filename);

  void clearScreen();
};
} // namespace Amazons

#endif

// ================== End of include/UI.h ==================

// ================== Start of src/Board.cpp ==================

namespace Amazons {
static const int dx[] = {1, 0, -1, 0, 1, -1, 1, -1};
static const int dy[] = {0, 1, 0, -1, 1, 1, -1, -1};
Board::Board() {
  for (int i = 0; i < GRIDSIZE; i++)
    for (int j = 0; j < GRIDSIZE; j++)
      grid[i][j] = EMPTY;
  grid[0][2] = grid[2][0] = grid[5][0] = grid[7][2] = grid_black;
  grid[0][5] = grid[7][5] = grid[2][7] = grid[5][7] = grid_white;
  blackPieces[0] = {0, 2};
  blackPieces[1] = {2, 0};
  blackPieces[2] = {5, 0};
  blackPieces[3] = {7, 2};
  whitePieces[0] = {0, 5};
  whitePieces[1] = {7, 5};
  whitePieces[2] = {2, 7};
  whitePieces[3] = {5, 7};
  turnID = 1;
}

bool Board::inMap(const Point &point) const {
  return (point.x >= 0 && point.x < GRIDSIZE && point.y >= 0 &&
          point.y < GRIDSIZE);
}

bool Board::isEmpty(const Point &point) const {
  return (grid[point.x][point.y] == EMPTY);
}

void Board::applyMove(const Move &move, int color) {
  grid[move.start.x][move.start.y] = EMPTY;
  grid[move.target.x][move.target.y] = color;
  grid[move.arrow.x][move.arrow.y] = OBSTACLE;
  Point *myPieces = (color == grid_black) ? blackPieces : whitePieces;
  for (int i = 0; i < 4; i++)
    if (myPieces[i] == move.start) {
      myPieces[i] = move.target;
      break;
    }
}

std::vector<Move> Board::getLegalMoves(int color) const {
  std::vector<Move> moves;
  const Point *pieces = (color == grid_black) ? blackPieces : whitePieces;
  for (int i = 0; i < 4; i++) {
    Point p = pieces[i];
    for (int dir = 0; dir < 8; dir++) {
      for (int step = 1;; ++step) {
        Point target_p = {static_cast<int8_t>(p.x + dx[dir] * step),
                          static_cast<int8_t>(p.y + dy[dir] * step)};
        if (!inMap(target_p) || !isEmpty(target_p))
          break;
        for (int obsDir = 0; obsDir < 8; ++obsDir) {
          for (int obsStep = 1;; ++obsStep) {
            Point arrow_p = {
                static_cast<int8_t>(target_p.x + dx[obsDir] * obsStep),
                static_cast<int8_t>(target_p.y + dy[obsDir] * obsStep)};
            if (!inMap(arrow_p))
              break;
            if (!isEmpty(arrow_p) && !(arrow_p == p))
              break;
            moves.push_back({p, target_p, arrow_p});
          }
        }
      }
    }
  }
  return moves;
}
int Board::countLegalMoves(
    int color) const { // 较快地计算数量，不考虑射箭，粗略估值
  int cntMoves = 0;
  const Point *pieces = (color == grid_black) ? blackPieces : whitePieces;
  for (int i = 0; i < 4; i++) {
    Point p = pieces[i];
    for (int dir = 0; dir < 8; dir++) {
      for (int step = 1;; ++step) {
        Point target_p = {static_cast<int8_t>(p.x + dx[dir] * step),
                          static_cast<int8_t>(p.y + dy[dir] * step)};
        if (!inMap(target_p) || !isEmpty(target_p))
          break;
        cntMoves++;
      }
    }
  }
  return cntMoves;
}
void Board::undoMove(const Move &move, int color) {
  grid[move.arrow.x][move.arrow.y] = EMPTY;
  grid[move.target.x][move.target.y] = EMPTY;
  grid[move.start.x][move.start.y] = color;
  Point *myPieces = (color == grid_black) ? blackPieces : whitePieces;
  for (int i = 0; i < 4; i++)
    if (myPieces[i] == move.target) {
      myPieces[i] = move.start;
      break;
    }
}
int Board::getGrid(const Point &point) const {
  return static_cast<int>(grid[point.x][point.y]);
}
int Board::getTurnID() const { return turnID; }
const Point *Board::getPieces(int color) const {
  return (color == grid_black) ? blackPieces : whitePieces;
}
int Board::loadBoard(const std::string &filename) {
  std::ifstream in;
  in.open(filename);
  if (!in) {
    std::cerr << "无法打开存档" << std::endl;
    return INFINITY;
  }
  int humanColor;
  in >> turnID;
  in >> humanColor;
  int countBlack = 0, countWhite = 0;
  for (int i = 0; i < GRIDSIZE; i++) {
    for (int j = 0; j < GRIDSIZE; j++) {
      int temp;
      in >> temp;
      grid[i][j] = (int8_t)temp;
      if (temp == grid_black)
        blackPieces[countBlack++] = {(int8_t)i, (int8_t)j};
      if (temp == grid_white)
        whitePieces[countWhite++] = {(int8_t)i, (int8_t)j};
      // board.grid[i][j] = temp;
      // if (temp == grid_white)
      //   board.whitePieces[countWhite++] = {i, j};
      // if (temp == grid_black)
      //   board.blackPieces[countBlack++] = {i, j};
    }
  }
  std::cout << "读盘成功" << std::endl;
  return humanColor;
}
} // namespace Amazons

// ================== End of src/Board.cpp ==================

// ================== Start of src/Human.cpp ==================

namespace Amazons {
Move humanPlayer::decideMove(const Board &board) {
  std::vector<Move> legalMoves = board.getLegalMoves(myColor);
  if (legalMoves.empty()) {
    std::cout << "你输了！" << std::endl;
    return MOVE_EXIT;
  }
  while (true) {
    std::cout << "请输入你的走法：(格式：x1 y1 x2 y2 x3 y3)" << std::endl;
    std::cout << "输入-1：暂停or存盘or退出:";
    int a[6];
    bool check = false;
    for (int i = 0; i < 6; i++) {
      int temp;
      while (!(std::cin >> temp)) {
        std::cin.clear();
        std::cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
      }
      if (temp == -1) {
        std::cout << "输入：" << std::endl;
        std::cout << "1:存盘并退出" << std::endl;
        std::cout << "2:直接退出" << std::endl;
        std::cout << "3.取消（返回棋局）" << std::endl;
        while (!(std::cin >> temp)) {
          std::cin.clear();
          std::cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
        }
        if (temp == 1) {
          return MOVE_SAVE;
        }
        if (temp == 2) {
          return MOVE_EXIT;
        }
        check = true;
        break;
      }
      a[i] = temp;
    }
    if (check) {
      std::cout << "返回成功，请重新输入坐标：";
      continue;
    }
    Move m = {(int8_t)a[0], (int8_t)a[1], (int8_t)a[2],
              (int8_t)a[3], (int8_t)a[4], (int8_t)a[5]};
    if (std::find(legalMoves.begin(), legalMoves.end(), m) !=
        legalMoves.end()) {
      return m;
    } else {
      std::cout << "非法落子！请重新输入：";
    }
  }
}
} // namespace Amazons

// ================== End of src/Human.cpp ==================

// ================== Start of src/AI.cpp ==================

namespace Amazons {

const int INF = 0x3f3f3f3f;
clock_t startTime;
struct sortableMove {
  Move move;
  int score;
  bool operator<(const sortableMove &other) const {
    return score > other.score;
  }
};
int posTable[8][8] = {
    {-5, -3, -1, -1, -1, -1, -3, -5}, {-3, 0, 1, 1, 1, 1, 0, -3},
    {-1, 1, 3, 3, 3, 3, 1, -1},       {-1, 1, 3, 4, 4, 3, 1, -1},
    {-1, 1, 3, 4, 4, 3, 1, -1},       {-1, 1, 3, 3, 3, 3, 1, -1},
    {-3, 0, 1, 1, 1, 1, 0, -3},       {-5, -3, -1, -1, -1, -1, -3, -5},
};

// int calDepth(int moveNum) {
//   if (moveNum >= 1500)
//     return 1;
//   if (moveNum <= 200 && moveNum >= 50)
//     return 2;
//   if (moveNum <= 50)
//     return 3;
//   return 2;
// }

void AIPlayer::queenBFS(const Board &board, int (*map)[8], int isMyself) {
  Point q[100];
  const Point *myPieces = board.getPieces(myColor * isMyself);
  memset(map, 0x3f, sizeof(int) * 8 * 8);
  int dx[] = {1, 0, -1, 0, 1, 1, -1, -1};
  int dy[] = {0, 1, 0, -1, 1, -1, 1, -1};
  int head = 0, tail = 0;
  for (int i = 0; i < 4; i++) {
    q[tail++] = myPieces[i];
    map[myPieces[i].x][myPieces[i].y] = 0;
  }
  while (head < tail) {
    Point top = q[head];
    head++;
    int px = top.x, py = top.y;
    int step = map[px][py];
    for (int i = 0; i < 8; i++) {
      for (int slide = 1;; slide++) {
        Point temp = {static_cast<int8_t>(px + dx[i] * slide),
                      static_cast<int8_t>(py + dy[i] * slide)};
        if (!board.inMap(temp))
          break;
        if (!board.isEmpty(temp))
          break;
        if (map[temp.x][temp.y] > step + 1) {
          map[temp.x][temp.y] = step + 1;
          q[tail++] = temp;
        }
      }
    }
  }
}
Move AIPlayer::decideMove(const Board &board) {
#ifndef _BOTZONE_ONLINE
  std::cout << "AI正在思考..." << std::endl;
#endif // !_BOTZONE_ONLINE
  startTime = clock();
  std::vector<Move> moves = board.getLegalMoves(myColor);
  if (moves.empty()) {
#ifndef _BOTZONE_ONLINE
    std::cout << "你赢了！" << std::endl;
#endif
    return MOVE_EXIT;
  }
  std::vector<sortableMove> sortablemoves;
  Board tempBoard = board;
  for (const auto &m : moves) {
    tempBoard.applyMove(m, myColor);
    int score = countMobility(tempBoard);
    sortablemoves.push_back({{m}, score});
    tempBoard.undoMove(m, myColor);
  }
  std::sort(sortablemoves.begin(), sortablemoves.end());
  for (size_t i = 0; i < sortablemoves.size(); ++i) {
    moves[i] = sortablemoves[i].move;
  }
  Move bestMove = moves[0];
  // int MAX_DEPTH = calDepth(moves.size());
  for (int depth = 1; depth <= 20; depth++) {
    int alpha = -1000000, beta = 1000000, currentBestscore = -1000000;
    Move currentBest = bestMove;
    bool TimeOut = false;
    for (auto it = moves.begin(); it != moves.end(); ++it) {
      tempBoard.applyMove(*it, myColor);
      int value = minimax(tempBoard, depth - 1, false, alpha, beta);
      if (value > currentBestscore) {
        alpha = value;
        currentBestscore = value;
        currentBest = *it;
      }
      tempBoard.undoMove(*it, myColor);
      double elapsed = (double)(clock() - startTime) / CLOCKS_PER_SEC;
      if (elapsed > 0.97) {
        TimeOut = true;
        break;
      }
    }
    if (!TimeOut)
      bestMove = currentBest;
    else
      break;
    double elapsed = (double)(clock() - startTime) / CLOCKS_PER_SEC;
    if (elapsed > 0.97)
      break;
  }
#ifndef _BOTZONE_ONLINE
  std::cout << "落子：(" << (int)bestMove.start.x << ","
            << (int)bestMove.start.y << "," << (int)bestMove.target.x << ","
            << (int)bestMove.target.y << "," << (int)bestMove.arrow.x << ","
            << (int)bestMove.arrow.y << ")" << std::endl;
  std::cout << "按回车键继续" << std::endl;
  std::cin.ignore();
  std::cin.get();
#endif
  return bestMove;
}

int AIPlayer::countMobility(const Board &board) {
  int myMoves = board.countLegalMoves(myColor);
  int opMoves = board.countLegalMoves(-myColor);
  return (myMoves - opMoves);
}

int AIPlayer::calQueenTerritory(const Board &board,
                                int myMap[GRIDSIZE][GRIDSIZE],
                                int opMap[GRIDSIZE][GRIDSIZE]) {
  int score = 0;
  for (int i = 0; i < GRIDSIZE; i++) {
    for (int j = 0; j < GRIDSIZE; j++) {
      if (board.getGrid({static_cast<int8_t>(i), static_cast<int8_t>(j)}) !=
          EMPTY)
        continue;
      if (myMap[i][j] > opMap[i][j])
        score--;
      if (myMap[i][j] < opMap[i][j])
        score++;
    }
  }
  return score;
}
int AIPlayer::calPosValue(const Board &board) {
  int score = 0;
  const Point *myPieces = board.getPieces(myColor);
  for (int i = 0; i < 4; i++) {
    score += posTable[myPieces[i].x][myPieces[i].y];
  }
  const Point *opPieces = board.getPieces(-myColor);
  for (int i = 0; i < 4; i++) {
    score -= posTable[opPieces[i].x][opPieces[i].y];
  }
  return score;
}
int AIPlayer::calTrapPenalty(const Board &board, int isMyself, int (*myMap)[8],
                             int (*opMap)[8]) {
  int dx[] = {1, 0, -1, 0, 1, 1, -1, -1};
  int dy[] = {0, 1, 0, -1, 1, -1, 1, -1};
  int score = 0;
  const Point *myPieces = board.getPieces(myColor * isMyself);
  int penalty[] = {-800, -200, -50, -5, 0, 0, 0, 0, 0};
  for (int i = 0; i < 4; i++) {
    Point p = myPieces[i];
    int liberties = 0;
    bool exitFlag = false;
    for (int j = 0; j < 8; j++) {
      Point temp = {static_cast<int8_t>(p.x + dx[j]),
                    static_cast<int8_t>(p.y + dy[j])};
      if (board.inMap(temp) && board.isEmpty(temp)) {
        liberties++;
        if (opMap[temp.x][temp.y] > myMap[temp.x][temp.y] + 1)
          exitFlag = true;
      }
    }
    if (!exitFlag)
      score += penalty[liberties];
  }
  return score;
}
int AIPlayer::evaluate(const Board &board) {
  int myDist[GRIDSIZE][GRIDSIZE];
  int opDist[GRIDSIZE][GRIDSIZE];
  queenBFS(board, myDist, 1);
  queenBFS(board, opDist, 1);
  int mobilityScore = countMobility(board);
  int territoryScore = calQueenTerritory(board, myDist, opDist);
  int myPenaltyScore = calTrapPenalty(board, 1, myDist, opDist);
  int opPenaltyScore = calTrapPenalty(board, -1, opDist, myDist);
  int posScore = calPosValue(board);
  double w_Mobility, w_Territory, w_Pos;
  double progress =
      (board.getTurnID() <= 30) ? (double)board.getTurnID() : 30.0;
  if (progress > 8.0)
    w_Pos = 0;
  else
    w_Pos = 2.0 - 2.0 * progress / 8.0;
  w_Territory = 0.1 + (10.0 - 0.1) * progress / 30.0;
  if (progress < 10.0)
    w_Mobility = 0.5 + (4.0 - 0.5) * (progress / 10.0);
  else
    w_Mobility = 4.0 - (progress - 10.0) / 20.0 * 4.0;
  double finalScore = (w_Territory * territoryScore) +
                      (w_Mobility * mobilityScore) + (w_Pos * posScore);
  finalScore += (myPenaltyScore - opPenaltyScore) / 2.0;
  return finalScore;
}

int AIPlayer::minimax(const Board &board, int depth, bool isMaximizing,
                      int alpha, int beta) {
  if (depth == 0) {
    return evaluate(board);
  }
  int currentColor = isMaximizing ? myColor : -myColor;
  std::vector<Move> moves = board.getLegalMoves(currentColor);
  if (moves.empty()) {
    return isMaximizing ? -1000000 : 1000000;
  }
  int score = isMaximizing ? -1000000 : 1000000;
  Board tempBoard = board;
  for (auto it = moves.begin(); it != moves.end(); ++it) {
    double elapsed = (double)(clock() - startTime) / CLOCKS_PER_SEC;
    if (elapsed > 0.97)
      return score;
    tempBoard.applyMove(*it, currentColor);
    int value = minimax(tempBoard, depth - 1, !isMaximizing, alpha, beta);
    if (isMaximizing) {
      if (value > alpha)
        alpha = value;
      if (value > score)
        score = value;
      if (alpha >= beta)
        break;
    } else {
      if (value < beta)
        beta = value;
      if (value < score)
        score = value;
      if (beta <= alpha)
        break;
    }
    tempBoard.undoMove(*it, currentColor);
  }
  return score;
}
} // namespace Amazons

// ================== End of src/AI.cpp ==================

// ================== Start of src/Interaction.cpp ==================

using namespace std;

namespace Amazons {
namespace Interaction {
int initAndRestore(Board &board) {
  int turnID;
  cin >> turnID;
  int myColor = grid_white;
  for (int i = 1; i <= turnID; i++) {
    int x0, y0, x1, y1, x2, y2;
    cin >> x0 >> y0 >> x1 >> y1 >> x2 >> y2;
    if (x0 == -1)
      myColor = grid_black;
    else {
      Move move = {{static_cast<int8_t>(x0), static_cast<int8_t>(y0)},
                   {static_cast<int8_t>(x1), static_cast<int8_t>(y1)},
                   {static_cast<int8_t>(x2), static_cast<int8_t>(y2)}};
      board.applyMove(move, -myColor);
    }
    if (i <= turnID - 1) {
      cin >> x0 >> y0 >> x1 >> y1 >> x2 >> y2;
      Move move = {{static_cast<int8_t>(x0), static_cast<int8_t>(y0)},
                   {static_cast<int8_t>(x1), static_cast<int8_t>(y1)},
                   {static_cast<int8_t>(x2), static_cast<int8_t>(y2)}};
      board.applyMove(move, myColor);
    }
    if (i != 1)
      board.addTurnID();
  }
  return myColor;
}

void outputMove(const Move &move) {
  printf("%d %d %d %d %d %d\n", move.start.x, move.start.y, move.target.x,
         move.target.y, move.arrow.x, move.arrow.y);
}
} // namespace Interaction
} // namespace Amazons

// ================== End of src/Interaction.cpp ==================

// ================== Start of src/UI.cpp ==================
#ifdef _WIN32
#include <windows.h>
#endif

using namespace std;

namespace Amazons {
Game::Game() : blackPlayer(nullptr), whitePlayer(nullptr), humanColor(0) {}
Game::~Game() {
  if (blackPlayer)
    delete blackPlayer;
  if (whitePlayer)
    delete whitePlayer;
}
void Game::clearScreen() {
#ifdef _WIN32
  system("cls");
#else
  system("clear");
#endif
}

void Game::run() {
#ifdef _WIN32
  SetConsoleOutputCP(65001);
#endif
  Player *human;
  Player *AI;
  while (true) {
    showMenu();
    int choice;
    cout << "请输入选项：";
    if (!(cin >> choice)) {
      cin.clear();
      cin.ignore(numeric_limits<streamsize>::max(), '\n');
    }
    switch (choice) {
    case 1:
      startNewGame();
      break;
    case 2:
      humanColor = board.loadBoard("saveGame.txt");
      if (humanColor == grid_black) {
        blackPlayer = new humanPlayer(grid_black);
        whitePlayer = new AIPlayer(grid_white);
      } else {
        whitePlayer = new humanPlayer(grid_white);
        blackPlayer = new AIPlayer(grid_black);
      }
      gameLoop(humanColor);
      break;
    case 3:
      cout << "Goodbye!" << endl;
      return;
    default:
      cout << "无效选项！" << endl;
      continue;
    }
  }
}

void Game::showMenu() {
  clearScreen();
  cout << "\n=========================" << endl;
  cout << "    亚马逊棋(Amazons)    " << endl;
  cout << "=========================" << endl;
  cout << "1.新游戏(New Game)" << endl;
  cout << "2.加载存档(Load Game)" << endl;
  cout << "3.结束(Exit)" << endl;
  cout << "=========================" << endl;
}

void Game::renderBoard() {
  clearScreen();
  cout << "\n当前回合：" << board.getTurnID() << endl;
  cout << "黑子：B     白子：W     障碍：X" << endl;
  cout << "你持" << ((humanColor == grid_black) ? "黑(B)" : "白(W)") << "子"
       << endl;
  cout << endl;
  cout << "    0   1   2   3   4   5   6   7  --> y" << endl;
  cout << "  ┌";
  for (int i = 0; i < 7; i++)
    cout << "───┬";
  cout << "───┐" << endl;

  for (int i = 0; i < 8; ++i) {
    // 2. 画中间的格子内容: │ . │ B │
    cout << i << " │"; // 行号 + 左边框
    for (int j = 0; j < 8; ++j) {
      int val = board.getGrid({static_cast<int8_t>(i), static_cast<int8_t>(j)});
      char symbol = ' ';
      if (val == grid_black)
        symbol = 'B'; // 或者用实心圆 ●
      else if (val == grid_white)
        symbol = 'W'; // 或者空心圆 ○
      else if (val == OBSTACLE)
        symbol = 'X';
      else
        symbol = ' ';

      cout << " " << symbol << " │"; // 棋子 + 右边框
    }
    cout << endl;

    // 3. 画行与行之间的分割线
    if (i < 7) {
      // 中间行: ├───┼───┤
      cout << "  ├";
      for (int k = 0; k < 7; k++)
        cout << "───┼";
      cout << "───┤" << endl;
    } else {
      // 最后一行底座: └───┴───┘
      cout << "  └";
      for (int k = 0; k < 7; k++)
        cout << "───┴";
      cout << "───┘" << endl;
    }
  }
  cout << "│" << endl << "│" << endl << "V x" << endl << endl;
}

void Game::gameLoop(int startColor) {
  int currentColor = startColor;
  while (true) {
    renderBoard();
    Move m;
    Player *currentPlayer =
        (currentColor == grid_black) ? blackPlayer : whitePlayer;
    m = currentPlayer->decideMove(board);
    if (m == MOVE_EXIT) {
      cout << "游戏结束" << endl;
      break;
    }
    if (m == MOVE_SAVE) {
      saveGame("saveGame.txt");
      cout << "已保存！按回车继续..." << endl;
      cin.get();
      cin.get();
      break;
    }
    board.applyMove(m, currentColor);
    if (currentColor == grid_white)
      board.addTurnID();
    currentColor = -currentColor;
  }
}

void Game::startNewGame() {
  board = Board();
  cout << "你想要选择黑（先手）还是白（后手）？" << endl;
  cout << "请输入：1(黑) or 2(白)" << endl;
  int choice;
  while (true) {
    while (!(cin >> choice)) {
      cin.clear();
      cin.ignore(numeric_limits<streamsize>::max(), '\n');
    }
    if (choice == 1 || choice == 2)
      break;
    cout << "请输入1或者2！" << endl;
    cout << "请输入：1(黑) or 2(白)" << endl;
  }
  humanColor = (choice == 1) ? grid_black : grid_white;
  if (humanColor == grid_black) {
    blackPlayer = new humanPlayer(grid_black);
    whitePlayer = new AIPlayer(grid_white);
  } else {
    whitePlayer = new humanPlayer(grid_white);
    blackPlayer = new AIPlayer(grid_black);
  }
  gameLoop(grid_black);
}

void Game::saveGame(const std::string &filename) {
  ofstream out;
  out.open(filename);
  if (!out) {
    cerr << "Error:无法保存存档！" << endl;
    return;
  }
  out << board.getTurnID() << endl;
  out << humanColor << endl;
  for (int i = 0; i < GRIDSIZE; i++) {
    for (int j = 0; j < GRIDSIZE; j++) {
      out << (int)board.getGrid(
                 {static_cast<int8_t>(i), static_cast<int8_t>(j)})
          << " ";
      // out << board.grid[i][j] << " ";
    }
    out << endl;
  }
  cout << "存档成功！" << endl;
}

void Game::loadGame(const std::string &filename) {
  humanColor = board.loadBoard(filename); // 返回人类玩家的颜色
}

} // namespace Amazons

// ================== End of src/UI.cpp ==================

// ================== Start of src/main.cpp ==================

using namespace Amazons;

int main() {
#ifdef _BOTZONE_ONLINE
  Board board;
  int myColor = Interaction::initAndRestore(board);
  AIPlayer ai(myColor);
  Move move = ai.decideMove(board);
  Interaction::outputMove(move);
  return 0;
#else
  Game game;
  game.run();
  return 0;
#endif // _BOTZONE_ONLINE
}

// ================== End of src/main.cpp ==================
