// Auto-generated by combine.py
// Please do not edit this file directly.

// Standard Libraries
#include <cerrno>
#include <iostream>
#include <vector>


// ================== Start of include/Defs.h ==================
#ifndef DEFS_H
#define DEFS_H


namespace Amazons {
const int GRIDSIZE = 8;
const int OBSTACLE = 2;
const int judge_black = 0;
const int judge_white = 1;
const int grid_black = 1;
const int grid_white = -1;
const int EMPTY = 0;

struct Point {
  int x, y;
  bool operator==(const Point &other) const {
    return x == other.x && y == other.y;
  }
};

struct Move {
  Point start;
  Point target;
  Point arrow;
};

struct Board {
  int grid[GRIDSIZE][GRIDSIZE];
  int turnID;
  Point blackPieces[4];
  Point whitePieces[4];
};
} // namespace Amazons

#endif // !DEFS_H

// ================== End of include/Defs.h ==================

// ================== Start of include/Logic.h ==================
#ifndef LOGIC_H
#define LOGIC_H


namespace Amazons {
namespace Logic {

void initBoard(Board &board);   // 用于初始化棋盘
bool inMap(const Point &point); // 用于判断是否在棋盘范围内
bool isEmpty(const Board &board, const Point &point); // 用于判断该点是否被占据
void applyMove(Board &board, const Move &move,
               int color); // 执行一步，改变棋盘状态
std::vector<Move> getLegalMoves(const Board &board,
                                int color); // 获取所有合法走法，返回一个vector

} // namespace Logic
} // namespace Amazons

#endif // !LOGIC_H

// ================== End of include/Logic.h ==================

// ================== Start of include/Interaction.h ==================
#ifndef INTERACTION_H
#define INTERACTION_H


namespace Amazons {
namespace Interaction {
int initAndRestore(Board &board);
void outputMove(const Move &move);
} // namespace Interaction
} // namespace Amazons

#endif

// ================== End of include/Interaction.h ==================

// ================== Start of include/AI.h ==================
#ifndef AI_H
#define AI_H


namespace Amazons {
namespace AI {
Move think(const Board &board, int myColor);
int evaluate(const Board &board, int myColor);
int minimax(const Board &board, int depth, bool isMaximizing, int myColor,
            int alpha, int beta);
} // namespace AI
} // namespace Amazons
#endif

// ================== End of include/AI.h ==================

// ================== Start of src/Logic.cpp ==================

namespace Amazons {
namespace Logic {
static const int dx[] = {1, 0, -1, 0, 1, -1, 1, -1};
static const int dy[] = {0, 1, 0, -1, 1, 1, -1, -1};
void initBoard(Board &board) {
  for (int i = 0; i < GRIDSIZE; i++)
    for (int j = 0; j < GRIDSIZE; j++)
      board.grid[i][j] = EMPTY;
  board.grid[0][2] = board.grid[2][0] = board.grid[5][0] = board.grid[7][2] =
      grid_black;
  board.grid[0][5] = board.grid[7][5] = board.grid[2][7] = board.grid[5][7] =
      grid_white;
  board.blackPieces[0] = {0, 2};
  board.blackPieces[1] = {2, 0};
  board.blackPieces[2] = {5, 0};
  board.blackPieces[3] = {7, 2};
  board.whitePieces[0] = {0, 5};
  board.whitePieces[1] = {7, 5};
  board.whitePieces[2] = {2, 7};
  board.whitePieces[3] = {5, 7};
  board.turnID = 1;
}

bool inMap(const Point &point) {
  return (point.x >= 0 && point.x < GRIDSIZE && point.y >= 0 &&
          point.y < GRIDSIZE);
}

bool isEmpty(const Board &board, const Point &point) {
  return (board.grid[point.x][point.y] == EMPTY);
}

void applyMove(Board &board, const Move &move, int color) {
  board.grid[move.start.x][move.start.y] = EMPTY;
  board.grid[move.target.x][move.target.y] = color;
  board.grid[move.arrow.x][move.arrow.y] = OBSTACLE;
  Point *myPieces =
      (color == grid_black) ? board.blackPieces : board.whitePieces;
  for (int i = 0; i < 4; i++)
    if (myPieces[i] == move.start) {
      myPieces[i] = move.target;
      break;
    }
}

std::vector<Move>
getLegalMoves(const Board &board,
              int color) { // 存在问题：关于被原有的点挡住了的问题
  std::vector<Move> moves;
  const Point *pieces =
      (color == grid_black) ? board.blackPieces : board.whitePieces;
  for (int i = 0; i < 4; i++) {
    Point p = pieces[i];
    for (int dir = 0; dir < 8; dir++) {
      for (int step = 1;; ++step) {
        Point target_p = {p.x + dx[dir] * step, p.y + dy[dir] * step};
        if (!inMap(target_p) || !isEmpty(board, target_p))
          break;
        for (int obsDir = 0; obsDir < 8; ++obsDir) {
          for (int obsStep = 1;; ++obsStep) {
            Point arrow_p = {target_p.x + dx[obsDir] * obsStep,
                             target_p.y + dy[obsDir] * obsStep};
            if (!inMap(arrow_p))
              break;
            if (!isEmpty(board, arrow_p) && !(arrow_p == p))
              break;
            moves.push_back({p, target_p, arrow_p});
          }
        }
      }
    }
  }
  return moves;
}
} // namespace Logic
} // namespace Amazons

// ================== End of src/Logic.cpp ==================

// ================== Start of src/Interaction.cpp ==================

using namespace std;

namespace Amazons {
namespace Interaction {
int initAndRestore(Board &board) {
  int turnID;
  cin >> turnID;
  Logic::initBoard(board);
  int myColor = grid_white;
  for (int i = 1; i <= turnID; i++) {
    int x0, y0, x1, y1, x2, y2;
    cin >> x0 >> y0 >> x1 >> y1 >> x2 >> y2;
    if (x0 == -1)
      myColor = grid_black;
    else {
      Move move = {{x0, y0}, {x1, y1}, {x2, y2}};
      Logic::applyMove(board, move, -myColor);
    }
    if (i <= turnID - 1) {
      cin >> x0 >> y0 >> x1 >> y1 >> x2 >> y2;
      Move move = {{x0, y0}, {x1, y1}, {x2, y2}};
      Logic::applyMove(board, move, myColor);
    }
  }
  board.turnID = turnID;
  return myColor;
}

void outputMove(const Move &move) {
  printf("%d %d %d %d %d %d\n", move.start.x, move.start.y, move.target.x,
         move.target.y, move.arrow.x, move.arrow.y);
}
} // namespace Interaction
} // namespace Amazons

// ================== End of src/Interaction.cpp ==================

// ================== Start of src/AI.cpp ==================

namespace Amazons {
namespace AI {
const int MAX_DEPTH = 2;
Move think(const Board &board, int myColor) {
  std::vector<Move> moves = Logic::getLegalMoves(board, myColor);
  if (moves.empty())
    return {{-1, -1}, {-1, -1}, {-1, -1}};
  int bestScore = -1000000, alpha = -1000000, beta = 1000000;
  Move bestMove = moves[0];
  for (auto it = moves.begin(); it != moves.end(); ++it) {
    Board tempBoard = board;
    Logic::applyMove(tempBoard, *it, myColor);
    int value;
    if (board.turnID == 1)
      value = minimax(tempBoard, 0, false, myColor, alpha, beta);
    else
      value = minimax(tempBoard, MAX_DEPTH - 1, false, myColor, alpha, beta);
    if (value > bestScore) {
      alpha = value;
      bestScore = value;
      bestMove = *it;
    }
  }
  return bestMove;
}
int evaluate(const Board &board, int myColor) {
  int myMoves = Logic::getLegalMoves(board, myColor).size();
  int opMoves = Logic::getLegalMoves(board, -myColor).size();
  return (myMoves - opMoves);
}
int minimax(const Board &board, int depth, bool isMaximizing, int myColor,
            int alpha, int beta) {
  if (depth == 0) {
    return evaluate(board, myColor);
  }
  int currentColor = isMaximizing ? myColor : -myColor;
  std::vector<Move> moves = Logic::getLegalMoves(board, currentColor);
  if (moves.empty()) {
    return isMaximizing ? -1000000 : 1000000;
  }
  int score = isMaximizing ? -1000000 : 1000000;
  for (auto it = moves.begin(); it != moves.end(); ++it) {
    Board tempBoard = board;
    Logic::applyMove(tempBoard, *it, currentColor);
    int value =
        minimax(tempBoard, depth - 1, !isMaximizing, myColor, alpha, beta);
    if (isMaximizing) {
      if (value > alpha)
        alpha = value;
      if (value > score)
        score = value;
      if (alpha >= beta)
        break;
    } else {
      if (value < beta)
        beta = value;
      if (value < score)
        score = value;
      if (beta <= alpha)
        break;
    }
  }
  return score;
}
} // namespace AI
} // namespace Amazons

// ================== End of src/AI.cpp ==================

// ================== Start of src/main.cpp ==================

using namespace Amazons;

int main() {
  Board board;
  int myColor = Interaction::initAndRestore(board);
  Move move = AI::think(board, myColor);
  Interaction::outputMove(move);
  return 0;
}

// ================== End of src/main.cpp ==================
