import os
import re

# ================= 配置区域 =================

# 输出文件名
OUTPUT_FILE = "submit.cpp"

# 要合并的文件列表
# 【注意】顺序非常重要！
# 1. 必须先放头文件 (.h)，后放源文件 (.cpp)
# 2. Defs.h 必须是第一个，因为它定义了基础结构体
# 3. 被依赖的文件要放在前面
MERGE_LIST = [
    "include/Defs.h",
    "include/Logic.h",
    "include/Interaction.h",
    "include/AI.h",
    "include/UI.h",
    "src/Logic.cpp",
    "src/Interaction.cpp",
    "src/AI.cpp",
    "src/UI.cpp",
    "src/main.cpp"
]

# ===========================================

def merge_files():
    # 用于存储标准库引用 (如 #include <vector>)，使用 set 自动去重
    std_includes = set()
    # 用于存储核心代码
    merged_content = []

    print(f"🚀 开始合并代码到 {OUTPUT_FILE} ...")

    for file_path in MERGE_LIST:
        if not os.path.exists(file_path):
            print(f"❌ 错误：找不到文件 {file_path}")
            return

        print(f"   -> 处理 {file_path}")
        
        with open(file_path, 'r', encoding='utf-8') as f:
            lines = f.readlines()
            
            merged_content.append(f"\n// ================== Start of {file_path} ==================\n")
            
            for line in lines:
                stripped = line.strip()
                
                # 1. 跳过 #pragma once
                if stripped.startswith("#pragma once"):
                    continue
                
                # 2. 收集标准库引用 (#include <...>)
                if stripped.startswith("#include <"):
                    # 如果是 windows.h，什么都不做，让它自然掉落到第4步被写入正文
                    if "windows.h" in stripped:
                        pass 
                    else:
                        # 如果是普通头文件，提取到顶部，并跳过本次循环
                        std_includes.add(stripped)
                        continue

                # 3. 跳过本地引用 (#include "...")
                # 因为所有代码都合并在一起了，不需要再 include 本地文件
                if stripped.startswith('#include "'):
                    continue
                
                # 4. 保留普通代码
                merged_content.append(line)
            
            merged_content.append(f"\n// ================== End of {file_path} ==================\n")

    # 开始写入最终文件
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as out:
        # 1. 写入头部注释
        out.write("// Auto-generated by combine.py\n")
        out.write("// Please do not edit this file directly.\n\n")
        
        # 2. 写入去重后的标准库引用
        out.write("// Standard Libraries\n")
        for inc in sorted(list(std_includes)):
            out.write(inc + "\n")
        out.write("\n")
        
        # 3. 写入合并后的代码主体
        out.writelines(merged_content)

    print(f"✅ 合并完成！生成文件大小: {os.path.getsize(OUTPUT_FILE)} bytes")

if __name__ == "__main__":
    merge_files()
